import React from "react";

function Head() {
  return <>
  <title>Next js | Blog App</title>
  <meta name="description" content="generated by next app"></meta>
  <link rel="icon" href="/favicon.ico" />
  </>;
}

export default Head;
